### ISSUE TITLE
Brackets are not escaped in xml files

### ISSUE THREAD

**Issue by KabbAmine** [Gemini-Loboto3/RE1-Mod-SDK#3]
`(` and `)` are needed in some text/*.xml files (At least in french), but they are not escaped and they give glitches in the game.
As a workaround, I'm using `[]` instead, and it does not bother me more than that, but it will be more logical to use brackets as intended, so how can I achieve that?

**Comment by Gemini-Loboto3** [comment]
Use "&#40;" and "&#41;", () are illegal characters.
