### ISSUE TITLE
Manual Aim

### ISSUE THREAD

**Issue by ProtOn-Gamer** [Gemini-Loboto3/RE1-Mod-SDK#5]
On all the PlayStation Versions of Resident Evil 1-3 you have an Option for manual aim instead of auto aim.
On the PC Versions only the Arrange Mode of Resident Evil 2 has manual aim, the other two PC games have not.
There is also a separate Restoration Project for Resident Evil 3 on Moddb, but you can not combine it with the
Rebirth Patch. This Restoration Project proves that it is possible to have manual aim for Resident Evil 3 on the PC.

**Comment by Gemini-Loboto3** [comment]
🤷

**Comment by ProtOn-Gamer** [comment]
What do you want to say with that?
When RE2 for PC has manual aim, why should it be impossible for the PC Versions of RE1 and RE3 to have manual aim?
I think you can do this with your knowledge and skills :-)

Thank you in advance, i appreciate your work a lot, it is very good!
